# Generated by Django 5.1.4 on 2025-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('promo_description', models.TextField(verbose_name='Описание акции')),
                ('promo_image', models.ImageField(upload_to='promos/', verbose_name='Изображение акции')),
                ('promo_start_date', models.DateField(verbose_name='Дата начала акции')),
                ('promo_end_date', models.DateField(verbose_name='Дата окончания акции')),
                ('promo_discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка')),
                ('promo_status', models.BooleanField(default=True, verbose_name='Статус')),
                ('promo_products', models.ManyToManyField(to='goods.product', verbose_name='Товары')),
            ],
        ),
    ]
