# Generated by Django 5.1.4 on 2025-02-07 05:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promo_promo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_color',
            field=colorfield.fields.ColorField(default='#acd5f5fc', image_field=None, max_length=25, samples=None),
        ),
    ]
