# Generated by Django 5.1.4 on 2025-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активность'),
        ),
    ]
