# Generated by Django 5.1.4 on 2025-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_courier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Возраст больше 18 подтвержден'),
        ),
    ]
