# Generated by Django 5.1.4 on 2025-02-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discaunt',
            field=models.IntegerField(default=0, verbose_name='Скидка по акциям'),
        ),
    ]
