# Generated by Django 5.1.4 on 2025-03-24 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('supply_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Поступление товара',
                'verbose_name_plural': 'Поступления товаров',
                'ordering': ['-supply_date'],
            },
        ),
    ]
