# Generated by Django 5.1.4 on 2025-01-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
