# Generated by Django 5.1.4 on 2025-03-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_productsupply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSupply',
        ),
    ]
