# Generated by Django 5.1.4 on 2025-01-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
