# Generated by Django 5.1.4 on 2025-01-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
