# Generated by Django 5.1.4 on 2025-02-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_category'),
        ('orders', '0003_order_delivery_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_items', to='goods.product', verbose_name='Товар'),
        ),
    ]
