# Generated by Django 5.1.4 on 2025-03-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_adress'),
        ('users', '0005_user_age_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adress', verbose_name='Адрес'),
        ),
    ]
